const express=require("express"),cors=require("cors"),compression=require("compression"),rateLimit=require("express-rate-limit"),http=require("http"),{Server}=require("socket.io");
require("dotenv").config();
const {connectDb}=require("./config/firebase");
const app=express();
app.set("trust proxy",1);
const server=http.createServer(app);
const ORIGENS=["https://tabuadaturbo.com.br","https://www.tabuadaturbo.com.br","https://meirelesnew.github.io","https://meirelesnew.github.io/frontend","http://localhost:3000","http://localhost:8080","http://127.0.0.1:5500"];
const io=new Server(server,{cors:{origin:ORIGENS,methods:["GET","POST"]}});
const PORT=process.env.PORT||10000;
app.use(compression());
app.use(cors({origin:ORIGENS,methods:["GET","POST","PUT","DELETE","HEAD","OPTIONS"],allowedHeaders:["Content-Type","Authorization"],credentials:true}));
app.use(express.json());
app.use("/api/auth",rateLimit({windowMs:15*60*1000,max:20,message:{error:"Muitas tentativas."},standardHeaders:true,legacyHeaders:false}));
app.use("/api",rateLimit({windowMs:60*1000,max:300,message:{error:"Muitas requisicoes."},standardHeaders:true,legacyHeaders:false}));
const salas=new Map();
io.on("connection",(socket)=>{
  let sA=null,jA=null;
  socket.on("criar_sala",({jogador_id:id,nome,avatar,nivel})=>{const c=Math.random().toString(36).substring(2,7).toUpperCase();const s={codigo:c,nivel,criador:{id,nome,avatar,socketId:socket.id,tempo:null,acertos:0,erros:0},jogadores:[],status:"esperando",createdAt:new Date()};salas.set(c,s);sA=c;jA={id,nome,avatar};socket.join(c);socket.emit("sala_criada",{codigo:c,sala:s});});
  socket.on("entrar_sala",({codigo,jogador_id:id,nome,avatar})=>{const c=codigo.toUpperCase();const s=salas.get(c);if(!s){socket.emit("erro",{message:"Sala nao encontrada"});return;}if(s.jogadores.length>=1||s.criador.id!==id)s.jogadores.push({id,nome,avatar,socketId:socket.id,tempo:null,acertos:0,erros:0});sA=c;jA={id,nome,avatar};socket.join(c);io.to(c).emit("jogador_entrou",{nome,avatar});socket.emit("sala_encontrada",{codigo:s.codigo,sala:s});});
  socket.on("iniciar_batalha",()=>{if(!sA)return;const s=salas.get(sA);if(!s)return;s.status="em_jogo";io.to(sA).emit("batalha_iniciada",{nivel:s.nivel});});
  socket.on("atualizar_progresso",({tempo,acertos,erros})=>{if(!sA||!jA)return;const s=salas.get(sA);if(!s)return;if(s.criador.id===jA.id)Object.assign(s.criador,{tempo,acertos,erros});else{const i=s.jogadores.findIndex(j=>j.id===jA.id);if(i!==-1)Object.assign(s.jogadores[i],{tempo,acertos,erros});}io.to(sA).emit("progresso_atualizado",{jogador:jA.nome,tempo,acertos,erros});});
  socket.on("finalizar_batalha",({tempo,acertos,erros})=>{if(!sA||!jA)return;const s=salas.get(sA);if(!s)return;if(s.criador.id===jA.id)Object.assign(s.criador,{tempo,acertos,erros});else{const i=s.jogadores.findIndex(j=>j.id===jA.id);if(i!==-1)Object.assign(s.jogadores[i],{tempo,acertos,erros});}const todos=[s.criador,...s.jogadores].filter(j=>j.tempo!==null);if(todos.length===s.jogadores.length+1){todos.sort((a,b)=>a.tempo-b.tempo);s.status="finalizada";io.to(sA).emit("batalha_finalizada",{resultados:todos});}else io.to(sA).emit("jogador_finalizou",{nome:jA.nome,tempo});});
  socket.on("sair_sala",()=>{if(!sA)return;const s=salas.get(sA);if(s){if(s.criador.id===jA?.id){s.status="cancelada";io.to(sA).emit("sala_cancelada");salas.delete(sA);}else{s.jogadores=s.jogadores.filter(j=>j.id!==jA?.id);io.to(sA).emit("jogador_saiu",{nome:jA?.nome});}}socket.leave(sA);sA=null;jA=null;});
  socket.on("disconnect",()=>{if(sA){const s=salas.get(sA);if(s&&s.status!=="finalizada"){io.to(sA).emit("adversario_desconectou");salas.delete(sA);}}});
});
app.use("/api/auth",require("./routes/auth"));
app.use("/api/ranking",require("./routes/ranking"));
app.use("/api/jogador",require("./routes/jogador"));
app.use("/api/admin",require("./routes/admin"));
app.all("/api/health",(req,res)=>res.json({status:"ok",versao:"4.0.0",db:"firestore",socketio:true}));
app.all("/",(req,res)=>res.json({status:"ok",app:"Tabuada Turbo API v4",db:"Firebase Firestore"}));
app.use((req,res)=>res.status(404).json({message:"Rota nao encontrada"}));
async function start(){try{await connectDb();server.listen(PORT,"0.0.0.0",()=>{console.log("\uD83D\uDE80 Tabuada Turbo API v4.0 — porta "+PORT);console.log("\uD83D\uDD25 Banco: Firebase Firestore");console.log("\uD83D\uDD10 Auth: Firebase Auth (email + Google)");});}catch(e){console.error("\u274C Falha:",e.message);process.exit(1);}}
start();
